mainapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('roomapp.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

roomapp/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path("customerdata/",views.customerdata,name="customerdata"),
    path("get_user/",views.get_user,name="get_user"),

    path('checkin/', views.checkin, name='checkin'),
    path('checkin_edit/<int:pk>/', views.checkin_edit, name='checkin_edit'),
    path('checkout/', views.checkout, name='checkout'),
    path('addroom/', views.addroom, name='addroom'),
    path('reserveroom/', views.reserveroom, name='reserveroom'),
    path('reservation_edit/<int:pk>/', views.reservation_edit, name='reservation_edit'),
    path('reservation_checkin/', views.reservation_checkin, name='reservation_checkin'),
    path('reservation_cancle/', views.reservation_cancle, name='reservation_cancle'),
    path('roommanager/', views.roommanager, name='roommanager'),
    path("room_update/",views.room_update,name="room_update"),
    path("room_delete/<str:pk>/",views.room_delete,name="room_delete"),
    path("report_gen/",views.report_gen,name="report_gen"),


    path('report/', views.customerdetail, name='report'),
    path('signin/', views.user_login, name='signin'),  
    path('signup/', views.user_signup, name='signup'),  
    path('logout/', views.user_logout, name='logout'),  
    path('with_room/', views.with_room, name='withroom'),
    
    path("withroom_update/<int:pk>/",views.order_update,name="withroom_update"),
    path("withroom_delete/<int:pk>/",views.order_delete,name="withroom_delete"),


    path('resturant/with_out_room/', views.with_out_room, name='withoutroom'),
    path('resturant/with_out_room_update/<int:pk>/', views.with_out_room_update, name='withoutroom_update'),
    path('resturant/with_out_room_delete/<int:pk>/', views.with_out_room_delete, name='withoutroom_delete'),



    path("get_room_by_group/",views.get_room_by_group,name="get_room_by_group"),
    path("check_out_process/",views.check_out_process,name="check_out_process"),
    path("check_out/",views.check_out,name="check_out"),


   
]

roomapp/models.py
from django.db import models
import random
import string
from datetime import date,timedelta





def random_string_generator(size=6, chars=string.ascii_lowercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

def random_user_generator(size=3, chars=string.ascii_lowercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))
# Create your models here.

class Customer(models.Model):
    full_name = models.CharField(max_length=255,blank=False)
    user = models.CharField(max_length=255,default = (f'#{random_string_generator()}').upper(),unique=False)    
    organization = models.CharField(max_length=255,null=True,blank=True)
    email = models.EmailField(max_length=255,null=True,blank=True)
    designation = models.CharField(max_length=255,blank=True)
    passport_id_number = models.CharField(max_length=255,blank=True)
    location = models.CharField(max_length=255,blank=True)
    phone_number = models.IntegerField(blank=False, help_text='Contact phone number',null=True)
    nationality = models.CharField(max_length=155,blank=True)
    remarks = models.CharField(max_length=255,blank=True)
    traval_agent = models.CharField(max_length=255,blank=True)
    bill_setteled_by = models.CharField(max_length=255,blank=True)
    booked_by = models.CharField(max_length=255,blank=False)
    check_in = models.DateTimeField(auto_now=False,null=True)
    check_out = models.DateTimeField(auto_now=False,null=True)
    main_id = models.ImageField(upload_to="customer/id",null=True,blank=True)


    
  
    
    def format_date(obj):
        return obj.check_in.strftime('%d %b %Y %H:%M')
    
    



    def __str__(self):
        return self.full_name
class Additional_id(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE,null=True)
    add_id = models.ImageField(upload_to="customer/add_id",null=True,blank=True)
    
class Grouped_room(models.Model):
    title = models.CharField(max_length=255,unique=True)

    def __str__(self):
        return self.title



class Room(models.Model):
    room_status = (
        ("available", "available"),
        ("booked","booked"),
        ("not-confirm","confirm"),
        ("cancled","cancled"),
        ("cleaning", "cleaning"),
        ("maintenance", "maintenance"),)
    room_number = models.CharField(max_length=255)
    group = models.ForeignKey(Grouped_room,on_delete=models.CASCADE,blank=True)
    price_pernight = models.CharField(max_length=255)
    status = models.CharField(max_length=255, choices=room_status, default="available")
    

    def __str__(self):
        return f"{self.room_number}"


class Booked(models.Model):
    customer_details = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    room_id = models.ManyToManyField(Room, blank=True)
    number_of_days = models.IntegerField(default=0,null=True ,blank=True)
    booked_date = models.DateTimeField(auto_now_add=True,null=True)
    child = models.IntegerField(default=0,null=True,blank=True)
    male_number = models.IntegerField(default=0,null=True,blank=True)
    female_number = models.IntegerField(default=0,null=True,blank=True)
    other_gender = models.IntegerField(default=0,null=True,blank=True)
    status = models.BooleanField(default=False)
    class Meta:
        ordering =["-booked_date"]
        
    @property
    def total_room(self):
        total_room = self.room_id.objects.all()
        return total_room

    def __str__(self):
        return f'{self.customer_details}'

    @property
    def business_days(self):
        holidays = Customer.objects.values_list('check_in', flat=True)
        oneday = timedelta(days=1)
        # print(oneday)
        dt = self.booked_date.date()
        # print("this is dt",dt)
        total_days = 0
        while (dt <= date.today()):
            if not dt.isoweekday() in (6, 7) and dt not in holidays.values():
                total_days += 1
            dt += oneday
        return total_days






class Advance_payment(models.Model):
    Payment_mode = (
        ("Esewa", "Eswa"),
        ("Khalti", "Khalti"),
        ("Bank Transfer", "Bank Transfer"),
        ("Cash", "Cash"),
        ("Other", "Other"),
    )
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    Advance_amount = models.CharField(max_length=255, blank=True)
    payment_day = models.DateTimeField(auto_now_add=True)
    payment_mode = models.CharField(
        max_length=255, choices=Payment_mode, default="available")
    remarks = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.customer.full_name


class Customer_list(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    # advance = models.ManyToManyField(Advance_payment,blank=True,null=True)
    checkin = models.DateTimeField(auto_now_add= True,null=True)
    checkout = models.CharField(max_length=255, default="stay")
    bookd_roooms = models.ForeignKey(
        Booked, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.customer.full_name

    @property
    def total_amount(self):
        total_amt = 0.0
        data = Advance_payment.objects.filter(customer=self.customer.id)
        print("this is data:",data)
        for d in data:
            total_amt += float(d.Advance_amount)
        if total_amt == 0.0:
            a = 0
        else:
            a = total_amt
        return a

    @property
    def total_resturent_amount(self):
        res_total = 0.0
        query = Order.objects.filter(
            customer=self.customer).all()
        for q in query:
            res_total += float(q.total)

        return res_total

    @property
    def room_cost(self):
        res_total = 0.0
        query = self.bookd_roooms.room_id.all()

        for q in query:
            res_total += float(q.price_pernight)

        return res_total

    @property
    def all_rooms(self):
        a = self.bookd_roooms.room_id.all()
        return a


class Ch_out(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    remaing_balance = models.FloatField(default=0,null=True)
    # resturent_bill = models.FloatField()
    room_bill = models.FloatField(default=0,null=True)
    # bar_bill = models.ForeignKey(Bar_items,on_delete=models.CASCADE)
    resturent_discount = models.FloatField(blank=True)
    # bar_discount = models.FloatField
    vat = models.BooleanField(default=False)
    room_discount = models.FloatField(blank=True)
    remarks = models.CharField(max_length=255 ,blank=True)

    def __str__(self) -> str:
        return self.customer.full_name

    @property
    def rem_bln(self):
        rem = self.remaing_balance
        if rem is None:
            rem =0
        else:
            rem = self.remaing_balance
        return rem
     
    

    @property
    def resturent_dic(self):
        return self.resturent_discount

    @property
    def room_dic(self):
        return self.room_discount




class Order(models.Model):
    order_id = models.CharField(max_length=255,default = (f'#{random_string_generator()}').upper(),unique=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True,null=True)
    room = models.ForeignKey(Room,on_delete=models.CASCADE,blank=True,null=True)
    
    total = models.CharField(max_length=255, null=True ,blank=True)
  
    order_date= models.DateTimeField(auto_now_add=True,null=True)

    def __str__(self):
        return f'{self.order_id}'


    
    @property
    def order_user(self):
        return f'{self.customer.full_name}'



class Non_room_user(models.Model):
    Payment_mode = (
        ("Esewa", "Eswa"),
        ("Khalti", "Khalti"),
        ("Bank Transfer", "Bank Transfer"),
        ("Cash", "Cash"),
        ("Other", "Other"),
    )
    order_id = models.CharField(max_length=255,default = (f'#{random_string_generator()}').upper(),unique=True)
    full_name = models.CharField(max_length=255,)
    phone_number = models.IntegerField()
    email = models.EmailField()
    total = models.FloatField(max_length=255, null=True ,blank=True)
    amount_paid = models.FloatField(default=0)
    remaing_amount = models.FloatField(default=0)
    Payment_mode = models.CharField(max_length=255,choices=Payment_mode,null=True,default="UNPAID")
    order_date = models.DateTimeField(auto_now_add=True,auto_now=False)
    


    def __str__(self):
        return f'{self.order_id } {self.full_name }'

templates/roomapp/addroom.html
{% extends 'base.html' %}



{% block content %}
<div class="container-fluid pt-4 px-4">
    <div class="bg-secondary rounded h-100 p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">Room Add</h6>
        </div>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} ">{{ message }}.</div>
       {% endfor %}
        {% endif %}

        <form action="" method="POST">

            {% csrf_token %}
           
        <div class="row">
           
            {% for field in form %}
            <div class="col-6">
                <div class="form-floating mb-3">
                    {{field}}
                    <label for="floatingInput">{{field.label}} :</label>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="row">
            <button type="submit" class="btn btn-warning rounded-pill m-2">Add Rooms</button>
        </div>
      
    </form>
    </div>
</div>

<!-- Recent Sales Start -->
<div class="container-fluid pt-4 px-4">
    <div class="bg-secondary text-center rounded p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">Room Status Managemenet </h6>
            <form class="d-none d-md-flex ms-4">
                <input class="form-control bg-dark border-0" type="search" placeholder="Search">
            </form>
        </div>
        <div class="table-responsive">
            <table class="table text-start align-middle table-bordered table-hover mb-0">
                <thead>
                    <tr class="text-white">
                        <th scope="col">Group </th>
                        <th scope="col">Room Number</th>                        
                        <th scope="col">Room Price</th>
                        <th scope="col">Room status </th>
                   
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for rooms in allrooms%}
                    <tr>
                        
                        <td>{{rooms.group.title}}</td>
                     <td>{{rooms.room_number}}</td>
                     <td>{{rooms.price_pernight}}</td>
                     <td>{{rooms.status}}</td>
                    
                        <td><a class="btn btn-sm btn-warning m-2" href="">Change </a><a class="btn btn-sm btn-primary " href="{% url 'room_delete' rooms.id %}"> Delete</a></td>
                    </tr>
                    {% endfor %}  
                </tbody>
            </table>
        </div>
    </div>
</div>




{% endblock content %}

templates/roomapp/check_in_edit.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid pt-4 px-4">
  <div class="bg-secondary rounded h-100 p-4">
      <div class="d-flex align-items-center justify-content-between mb-4">
          <h6 class="mb-0">Room Reservation Form</h6>
          <button type="button" id="clear_form" class="btn btn-warning rounded-pill m-2">Clear</button>

      </div>

      <div class="row">
          
       
          {% if messages %}
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }} ">{{ message }}.</div>
         {% endfor %}
          {% endif %}
      <form id= "configform"action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
      <div class="row">
          {% if form.errors %}
          {% for field in form %}
          {% for error in field.errors %}
          <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
          </div>
          {% endfor %}
          {% endfor %}
      
          {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
          </div>
          {% endfor %}
      
          {% endif %}
          {% for fields in form%}
          <div class="col-6">
              <div class="form-floating mb-3">
                  {{fields.label}}
                  {{fields}}
                  
              </div>
          </div>
          {% endfor %}
      </div>
      <div class="row">
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
    
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
    
        {% endif %}
        
        {% for fields in customer_form.visible_fields %}
                    <div class="col-6">
                        {{ fields.errors }}
                        {{ fields.label_tag }}
                        {{ fields }}
                    </div>
                    {% endfor %}
                    <div class="col-6" style="display:none;">
                        {% for field in customer_form.hidden_fields %}
                        <div style="display:none;">{{ field }}</div>
                        {% endfor %}
                </div>
        {% for fields in book_form %}
        <div class="col-6">
            <div class="form-floating mb-3">
                {{fields.label}}
                {{fields}}
                
            </div>
        </div>
      
        {% endfor %}
    </div>
    
      <div class="row">
          <button type="submit"  class="btn btn-warning rounded-pill my-2">Save</button>
      </div>
  </form>
  </div>
</div>

{% block scripts %}
<script>
    $(document).ready(function(){
    
    
    var room_id = $("#id_room");
    room_id.select2({
      placeholder: 'Select Room id'
    })
    
    $("#id_payment_type").select2({
      placeholder: 'Choose Payment Type'
    })
    
    var gc_room = $("#gc-room")
    gc_room.select2({
      placeholder: 'Select room Group',
      ajax: {
        url: "{% url 'get_room_by_group' %}",
        dataType: 'json',
        processResults:function(data){
          return{
            results:$.map(data,function(item){
              return {id:item.id,text:item.title}
            })
          }
        },
        
    
      }
    })
    gc_room.on("select2:select",function(e){
      var data = e.params.data;
      $.ajax({
        url:"{% url 'checkin' %}",
        dataType:"json",
        data:{"room":data.text},
        success:function(resp){
         
         
    
          room_id.select2({
            // allowClear: true,
            data:$.map(resp,function(item){
             return {id:item.id,text:item.room_number}
            })
          })
        }
        
      })
      
    })
    });
    </script>


{% endblock scripts %}
{% endblock content %}

templates/roomapp/checkin.html
{% extends 'base.html' %}
{% block content %}  
<!-- Sale & Revenue Start -->

<!-- Button trigger modal -->

  <!-- Modal -->
  <div class="modal fade" id="preview" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title text-dark" id="exampleModalLabel">Summery </h5>
          
        </div>
        <div class="modal-body">
            <div id="cus_details">
            </div>
            <div class="img_preview">
                <img id="file-ip-1-preview">
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" onclick="preview()" >Close</button>
        </div>
      </div>
    </div>
  </div>

<div class="modal fade none-border" id="x_payment" >
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><strong>Pay Advance </strong></h4>
            </div>
            <div class="modal-body">
                <div id="py-up">
                    <div class="text-center">
                        <div class="spinner-border" role="status">
                            <span class="sr-only">Loading...</span>
                        </div>
                    </div>
                </div>
                <form id="payform">

                    {% csrf_token %}

                    <div class="row">


                        {% for field in form2 %}
                        <div class="col-md-6">

                            <label class="control-label" for="{{ field.auto_id }}">{{ field.label }}</label>
                            {{ field }}
                        </div>
                        {% endfor %}
                    </div>
                    <div class="modal-footer">
                        <button type="button" id="proced_pay"
                            class="btn btn-danger waves-effect waves-light save-category" data-dismiss="modal">Proceed
                            To Pay</button>
                    </div>
                </form>
            </div>


        </div>
    </div>
</div>

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-6 col-xl-3">
            <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                <i class="fa fa-chart-line fa-3x text-primary"></i>
                <div class="ms-3">
                    <p class="mb-2">Today Room</p>
                    <h6 class="mb-0">24</h6>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-xl-3">
            <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                <i class="fa fa-chart-bar fa-3x text-primary"></i>
                <div class="ms-3">
                    <p class="mb-2">Avilable Room</p>
                    <h6 class="mb-0">4</h6>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-xl-3">
            <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                <i class="fa fa-chart-area fa-3x text-primary"></i>
                <div class="ms-3">
                    <p class="mb-2">Room Cleaning</p>
                    <h6 class="mb-0">4</h6>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-xl-3">
            <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                <i class="fa fa-chart-pie fa-3x text-primary"></i>
                <div class="ms-3">
                    <p class="mb-2">Booked Room</p>
                    <h6 class="mb-0">4</h6>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Sale & Revenue End -->

<div class="container-fluid pt-4 px-4">
    <div class="bg-secondary rounded h-100 p-4">
        <div class="d-flex align-items-center justify-content-between mb-4" id="data-rooms">
            <h6 class="mb-0">Check In Customer</h6>
        
            <h6 class="mb-0" id = "prev_room">Previous Room  </h6>
            <h6 class="mb-0" id = "prev_room_disc">Prevvious room discount</h6>
        <button type="button" id="clear_form" class="btn btn-warning rounded-pill m-2">Clear</button>
        </div>

        <div class="row">
            <div class="form-floating mb-3">
                <input type="text"  class="form-control" id="floatingInput"
                    placeholder="Ram Shah">
                <label for="floatingInput">  &nbsp;&nbsp; Search</label>
            </div>
           
        </div>

       
            {% if form.errors %}
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
        
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
        
            {% endif %}

            <form  id = "configform" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                 <div class="row updated_form">

                

                    {% for fields in form.visible_fields %}
                    <div class="col-6">
                        {{ fields.errors }}
                        {{ fields.label_tag }}
                        {{ fields }}
                    </div>
                    {% endfor %}
                    <div class="col-6" style="display:none;">
                        {% for field in form.hidden_fields %}
                        <div style="display:none;">{{ field }}</div>
                        {% endfor %}
                    </div>
                </div>
                <div class="row">
                <div class="col-6">
                    <div class="">
                        Room
                        <select type="text" name="gc-room" class="form-control mt-2" maxlength="255"
                            id="gc-room" required></select>
                    </div>
                </div>
                <div class="col-6">
                    <div class="">
                        Room Number
                        <select type="text" name="id_room" class="form-control mt-2" name="id_room[]"
                            maxlength="255" id="id_room" multiple="multiple" required></select>
                    </div>
                    
                </div>
                <button type="submit" class="btn btn-warning rounded-pill m-2">Save</button>

            </div>
        </form>
            <div class="row">
                <button  onclick="preview()" type="button" class="btn btn-primary">
                   Preview
                  </button>
                       
        </div>

      
</div>

<!-- Recent Sales Start -->
<div class="container-fluid pt-4 px-4">
    <div class="bg-secondary text-center rounded p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">Customer Status Managemenet </h6>
            <form class="d-none d-md-flex ms-4">
                <input class="form-control bg-dark border-0" type="search" placeholder="Search">
            </form>
        </div>
        <div class="table-responsive">
            <table class="table text-start align-middle table-bordered table-hover mb-0">
                <thead>
                    <tr role="row">
                        <th>Customer Full Name</th>
                        <th>Phone Number</th>
                        <th>Restaurant Bills</th>
                        <th>Rooms</th>
                        <th>Check In </th>

                        <th>Action</th>

                    </tr>
                </thead>
                <tbody>
                    {% for cus in customer_list %}
                    <tr class="odd" role="row">
                        <td class="sorting_1" id="user_id">{{cus.customer.full_name}}</td>

                        <td>{{cus.customer.phone_number}}</td>

                        <td>



                        </td>

                        <td> {% for r in cus.bookd_roooms.room_id.all %}

                            <span
                                class="badge badge-xs badge-success">{{r.room_number|upper}}</span>
                            {% endfor %}
                        </td>


                        <td>{{cus.customer.check_in|date:"Y-m-d h : m A "}}</td>



                        <td><span>
                            <button type="button" class="btn btn-success btn-sm"
                            onclick="ad_pay({{cus.customer.id}})" id="ad_pay">Pay Advance
                            <span class="btn-icon-start"><i class="fas fa-money-bill-wave"></i></span>
                        </button>
                                <a href="{% url 'checkin_edit' cus.customer.id %}" type="button" class="btn btn-primary" >Edit  <span
                                        class="btn-icon-start"><i class="fas fa-clipboard"></i></span></a>
                        </td>
                    </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% block scripts %}
<script>
$(document).ready(function(){


var room_id = $("#id_room");
room_id.select2({
  placeholder: 'Select Room id'
})



var gc_room = $("#gc-room")
gc_room.select2({
  placeholder: 'Select room Group',
  ajax: {
    url: "{% url 'get_room_by_group' %}",
    dataType: 'json',
    processResults:function(data){
      return{
        results:$.map(data,function(item){
          return {id:item.id,text:item.title}
        })
      }
    },
    

  }
})
gc_room.on("select2:select",function(e){
  var data = e.params.data;
  $.ajax({
    url:"{% url 'checkin' %}",
    dataType:"json",
    data:{"room":data.text},
    success:function(resp){
     
     

      room_id.select2({
        // allowClear: true,
        data:$.map(resp,function(item){
         return {id:item.id,text:item.room_number}
        })
      })
    }
    
  })
  
});

});
function ad_pay(b) {
    $("#py-up").hide()

    $('#x_payment').modal('toggle')
    var user = b;

    let csr = $("input[name=csrfmiddlewaretoken]").val()



    $("#proced_pay").unbind("click").bind("click", function () {
        var amount = $("#id_Advance_amount").val();
        var paytype = $('#id_payment_type').find(':selected').val();
        var remarks = $('#id_remarks').val();
        var cred = {
            "user": user,

            "ammount": amount,
            "paytype": paytype,
            "remarks": remarks
        }
        $.ajax({
            method: 'POST',
            url: '{% url "checkout" %}',
            dataType: "json",
            headers: { "X-CSRFToken": csr, },
            data: cred,
            beforesend: function () {
                $("#py-up").show()
            },
            success: function (response) {

                if (response.message == "success") {
                    $("#x_payment").modal('toggle');
                    $.notify("Payment has been made ", "success");

                } else {
                    $.notify("Payments cant made !", "alert");
                }

            },
            complete: function () {
                console.log("done")
                
                $("#py-up").hide()

            }

        });
        $("#payform")[0].reset();


    });


}

function preview(){
    $('#preview').modal('toggle')
     var full_name =   $("#id_full_name").val();
     var user_id=   $("#id_user").val();
     var organization =   $("#id_organization").val();
     var designation =   $("#id_designation").val();
     var passport_id_number=   $("#id_passport_id_number").val();
     var location=   $("#id_location").val();
     var phone_number=   $("#id_phone_number").val();
    var nationality =    $("#id_nationality").val();
     var tel_fax=   $("#id_tel_fax").val();
     var traval_agent=   $("#id_traval_agent").val();
      var bill_setteled_by =  $("#id_bill_setteled_by").val();
      var booked_by = $("#id_booked_by").val();
      var remarks=  $("#id_remarks").val();
    //var image_url = $("#id_main_id").wrap(`<span class="mt-3" >${data["customer"][0]['main_id']}</span>`)
    $("#cus_details").html(
        
    `Full Name : ${full_name} <br>
     Organization: ${organization}<br>
     designation: ${designation}<br>
     passport_id_number: ${passport_id_number}<br>
     phone_number: ${phone_number}<br>
     nationality: ${nationality}<br>
     tel_fax: ${tel_fax}<br>
     traval_agent: ${traval_agent}<br>
     bill_setteled_by: ${bill_setteled_by}<br>
     booked_by: ${booked_by}<br>
     remarks: ${remarks}<br>

     `
    

    )
  

}



</script>



{% endblock scripts %}






<!-- Recent Sales End -->
{% endblock %} 

templates/roomapp/index.html
{% extends 'base.html' %}