mainapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('roomapp.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resturentapp/models.py
from django.db import models

# Create your models here.

roomapp/models.py
from django.db import models
import random
import string
from datetime import date,timedelta





def random_string_generator(size=6, chars=string.ascii_lowercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

def random_user_generator(size=3, chars=string.ascii_lowercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))
# Create your models here.

class Customer(models.Model):
    full_name = models.CharField(max_length=255,blank=False)
    user = models.CharField(max_length=255,default = (f'#{random_string_generator()}').upper(),unique=False)    
    organization = models.CharField(max_length=255,null=True,blank=True)
    email = models.EmailField(max_length=255,null=True,blank=True)
    designation = models.CharField(max_length=255,blank=True)
    passport_id_number = models.CharField(max_length=255,blank=True)
    location = models.CharField(max_length=255,blank=True)
    phone_number = models.IntegerField(blank=False, help_text='Contact phone number',null=True)
    nationality = models.CharField(max_length=155,blank=True)
    remarks = models.CharField(max_length=255,blank=True)
    traval_agent = models.CharField(max_length=255,blank=True)
    bill_setteled_by = models.CharField(max_length=255,blank=True)
    booked_by = models.CharField(max_length=255,blank=False)
    check_in = models.DateTimeField(auto_now=False,null=True)
    check_out = models.DateTimeField(auto_now=False,null=True)
    main_id = models.ImageField(upload_to="customer/id",null=True,blank=True)


    
  
    
    def format_date(obj):
        return obj.check_in.strftime('%d %b %Y %H:%M')
    
    



    def __str__(self):
        return self.full_name
class Additional_id(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE,null=True)
    add_id = models.ImageField(upload_to="customer/add_id",null=True,blank=True)
    
class Grouped_room(models.Model):
    title = models.CharField(max_length=255,unique=True)

    def __str__(self):
        return self.title



class Room(models.Model):
    room_status = (
        ("available", "available"),
        ("booked","booked"),
        ("not-confirm","confirm"),
        ("cancled","cancled"),
        ("cleaning", "cleaning"),
        ("maintenance", "maintenance"),)
    room_number = models.CharField(max_length=255)
    group = models.ForeignKey(Grouped_room,on_delete=models.CASCADE,blank=True)
    price_pernight = models.CharField(max_length=255)
    status = models.CharField(max_length=255, choices=room_status, default="available")
    

    def __str__(self):
        return f"{self.room_number}"


class Booked(models.Model):
    customer_details = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    room_id = models.ManyToManyField(Room, blank=True)
    number_of_days = models.IntegerField(default=0,null=True ,blank=True)
    booked_date = models.DateTimeField(auto_now_add=True,null=True)
    child = models.IntegerField(default=0,null=True,blank=True)
    male_number = models.IntegerField(default=0,null=True,blank=True)
    female_number = models.IntegerField(default=0,null=True,blank=True)
    other_gender = models.IntegerField(default=0,null=True,blank=True)
    status = models.BooleanField(default=False)
    class Meta:
        ordering =["-booked_date"]
        
    @property
    def total_room(self):
        total_room = self.room_id.objects.all()
        return total_room

    def __str__(self):
        return f'{self.customer_details}'

    @property
    def business_days(self):
        holidays = Customer.objects.values_list('check_in', flat=True)
        oneday = timedelta(days=1)
        # print(oneday)
        dt = self.booked_date.date()
        # print("this is dt",dt)
        total_days = 0
        while (dt <= date.today()):
            if not dt.isoweekday() in (6, 7) and dt not in holidays.values():
                total_days += 1
            dt += oneday
        return total_days






class Advance_payment(models.Model):
    Payment_mode = (
        ("Esewa", "Eswa"),
        ("Khalti", "Khalti"),
        ("Bank Transfer", "Bank Transfer"),
        ("Cash", "Cash"),
        ("Other", "Other"),
    )
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    Advance_amount = models.CharField(max_length=255, blank=True)
    payment_day = models.DateTimeField(auto_now_add=True)
    payment_mode = models.CharField(
        max_length=255, choices=Payment_mode, default="available")
    remarks = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.customer.full_name


class Customer_list(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    # advance = models.ManyToManyField(Advance_payment,blank=True,null=True)
    checkin = models.DateTimeField(auto_now_add= True,null=True)
    checkout = models.CharField(max_length=255, default="stay")
    bookd_roooms = models.ForeignKey(
        Booked, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.customer.full_name

    @property
    def total_amount(self):
        total_amt = 0.0
        data = Advance_payment.objects.filter(customer=self.customer.id)
        print("this is data:",data)
        for d in data:
            total_amt += float(d.Advance_amount)
        if total_amt == 0.0:
            a = 0
        else:
            a = total_amt
        return a

    @property
    def total_resturent_amount(self):
        res_total = 0.0
        query = Order.objects.filter(
            customer=self.customer).all()
        for q in query:
            res_total += float(q.total)

        return res_total

    @property
    def room_cost(self):
        res_total = 0.0
        query = self.bookd_roooms.room_id.all()

        for q in query:
            res_total += float(q.price_pernight)

        return res_total

    @property
    def all_rooms(self):
        a = self.bookd_roooms.room_id.all()
        return a


class Ch_out(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    remaing_balance = models.FloatField(default=0,null=True)
    # resturent_bill = models.FloatField()
    room_bill = models.FloatField(default=0,null=True)
    # bar_bill = models.ForeignKey(Bar_items,on_delete=models.CASCADE)
    resturent_discount = models.FloatField(blank=True)
    # bar_discount = models.FloatField
    vat = models.BooleanField(default=False)
    room_discount = models.FloatField(blank=True)
    remarks = models.CharField(max_length=255 ,blank=True)

    def __str__(self) -> str:
        return self.customer.full_name

    @property
    def rem_bln(self):
        rem = self.remaing_balance
        if rem is None:
            rem =0
        else:
            rem = self.remaing_balance
        return rem
     
    

    @property
    def resturent_dic(self):
        return self.resturent_discount

    @property
    def room_dic(self):
        return self.room_discount




class Order(models.Model):
    order_id = models.CharField(max_length=255,default = (f'#{random_string_generator()}').upper(),unique=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True,null=True)
    room = models.ForeignKey(Room,on_delete=models.CASCADE,blank=True,null=True)
    
    total = models.CharField(max_length=255, null=True ,blank=True)
  
    order_date= models.DateTimeField(auto_now_add=True,null=True)

    def __str__(self):
        return f'{self.order_id}'


    
    @property
    def order_user(self):
        return f'{self.customer.full_name}'



class Non_room_user(models.Model):
    Payment_mode = (
        ("Esewa", "Eswa"),
        ("Khalti", "Khalti"),
        ("Bank Transfer", "Bank Transfer"),
        ("Cash", "Cash"),
        ("Other", "Other"),
    )
    order_id = models.CharField(max_length=255,default = (f'#{random_string_generator()}').upper(),unique=True)
    full_name = models.CharField(max_length=255,)
    phone_number = models.IntegerField()
    email = models.EmailField()
    total = models.FloatField(max_length=255, null=True ,blank=True)
    amount_paid = models.FloatField(default=0)
    remaing_amount = models.FloatField(default=0)
    Payment_mode = models.CharField(max_length=255,choices=Payment_mode,null=True,default="UNPAID")
    order_date = models.DateTimeField(auto_now_add=True,auto_now=False)
    


    def __str__(self):
        return f'{self.order_id } {self.full_name }'

resturentapp/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render_to_response
from django.template import RequestContext


def handler404(request, *args, **argv):
    response = render_to_response('404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response

templates/resturentapp/without_room_update.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid pt-4 px-4">
    <div class="bg-secondary rounded h-100 p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">Room Reservation Form</h6>
            <button type="button" id="clear_form" class="btn btn-warning rounded-pill m-2">Clear</button>

        </div>

        <div class="row">
            
         
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} ">{{ message }}.</div>
           {% endfor %}
            {% endif %}
        <form id= "configform"action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
        <div class="row">
            {% if form.errors %}
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
        
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
        
            {% endif %}
            {% for fields in form%}
            <div class="col-6">
                <div class="form-floating mb-3">
                    {{fields.label}}
                    {{fields}}
                    
                </div>
            </div>
            {% endfor %}
        </div>
      
        <div class="row">
            <button type="submit"  class="btn btn-warning rounded-pill my-2">Update</button>
        </div>
    </form>
    </div>
</div>


{% endblock content %}

templates/resturentapp/withoutroom.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container-fluid pt-4 px-4">
    <div class="bg-secondary rounded h-100 p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">Order Creation Form</h6>

        </div>
        <div class="row">
            
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} ">{{ message }}.</div>
                {% endfor %}
                {% endif %}
                <div class="row">
                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
                {% endfor %}

                {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}

                {% endif %}
            </div>
                <form action="" method="post">
                    {% csrf_token %}
                        <div class="row">
                        {% for field in form %}
                        <div class="form-group col-6">
                            {{field.label}} :
                            {{field}}
                        </div>
                        {% endfor %}
                        <button type="submit" id="orderCreate" class="btn btn-primary">Create Order</button>
                    </div>


                </form>
        </div>
    </div>
</div>
<div class="container-fluid pt-4 px-4">
    <div class="bg-secondary text-center rounded p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">Customer Status Managemenet </h6>
            <form class="d-none d-md-flex ms-4">
                <input class="form-control bg-dark border-0" type="search" placeholder="Search">
            </form>
        </div>
        <div class="table-responsive">
            <table class="table text-start align-middle table-bordered table-hover mb-0">
                <thead>
                    <tr role="row">
                        <th>Order ID</th>
                        <th>Customer</th>
                        <th>Phone Number</th>
                        <th>Email</th>
                        <th>Order Date</th>
                        
                        <th>Total</th>
                        <th>Remaing amount</th>
                        <th>Payment Mode</th>
                        <th>Action</th>
                
                    </tr>
                </thead>
                <tbody>
                    {% for cus in non_room_user %}
                
                    <tr class="odd" role="row">
                        <td class="sorting_1" id="user_id">{{cus.order_id}}</td>
                        <td>{{cus.full_name}}</td>
                        <td>{{cus.phone_number}}</td>
                        <td>{{cus.email}}</td>
                        <td>{{cus.order_date}}</td>
                        <td>{{cus.total}}</td>
                        <td>{{cus.remaing_amount}}</td>
                        <td>{{cus.Payment_mode}}</td>
                       
                      
                        
                
                
                
                        <td>
                                <a class="btn btn-primary" href="{% url 'withoutroom_update' cus.id %}"
                                    class="my-4 update_customer"><i
                                        class="fa fa-pencil color-muted"></i> Order Update</a>
                                
                                        <a class="btn btn-warning" href="{% url 'withoutroom_delete' cus.id %}"><i
                                        class="fa fa-close color-danger"></i>Delete</a>
                        </td>
                    </tr>
                
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% block scripts %}
<script>

$("#id_amount_paid").keyup(function(){

    var total = $("#id_total").val();
    var amount_paid = $("#id_amount_paid").val();

    var remaing_amt = total-amount_paid


    $("#id_remaing_amount").val(remaing_amt)

})

</script>

{% endblock scripts %}

{% endblock content %}

templates/resturentapp/withroom.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid pt-4 px-4">
    <div class="bg-secondary rounded h-100 p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">Order Creation Form</h6>

        </div>
        <div class="row">
            
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} ">{{ message }}.</div>
                {% endfor %}
                {% endif %}
                <div class="row">
                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
                {% endfor %}

                {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}

                {% endif %}
            </div>
                <form action="">
                    {% csrf_token %}
                   
                        {% for field in form %}
                        <div class="form-group col-6">
                            {{field.label}} :
                            {{field}}
                        </div>
                        {% endfor %}
                        <button type="button" id="orderCreate" class="btn btn-primary">Create Order</button>
                 


                </form>
        </div>
    </div>
</div>
    <div class="row order1">
        <div class="col-12">
            <div class="card">
                <div class="card-header pb-0">
                    <h4 class="card-title text-dark">Room Customer</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <div id="employees_wrapper" class="dataTables_wrapper">


                            <table id="customer" class="display dataTable" style="min-width: 845px" role="grid"
                                aria-describedby="employees_info">
                                <thead>
                                    <tr role="row">
                                        <th>Order ID</th>
                                        <th>Room number</th>

                                        <th>Total</th>
                                        <th>Order Date</th>
                                        <th>Action</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    {% for cus in order %}

                                    <tr class="odd" role="row">
                                        <td class="sorting_1" id="user_id">{{cus.order_id}}</td>
                                        <td>{{cus.room.room_number}} </td>

                                        <td>{{cus.total}}</td>

                                        <td>{{cus.order_date}}</td>



                                        <td><span>
                                                <a class="btn btn-primary my-1 mx-1"
                                                    href="{% url 'withroom_update' cus.id %}"
                                                    class="mr-4 update_customer"><i
                                                        class="fa fa-pencil color-muted"></i> Update</a>
                                                
                                        </td>
                                    </tr>

                                    {% endfor %}
                                </tbody>

                            </table>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% block scripts %}




    {% endblock scripts %}
    {% endblock content %}

templates/resturentapp/withroom_update.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid pt-4 px-4">
    <div class="bg-secondary rounded h-100 p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">Room Reservation Form</h6>
            <button type="button" id="clear_form" class="btn btn-warning rounded-pill m-2">Clear</button>

        </div>

        <div class="row">
            
         
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} ">{{ message }}.</div>
           {% endfor %}
            {% endif %}
        <form id= "configform"action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
        <div class="row">
            {% if form.errors %}
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
        
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
        
            {% endif %}
            {% for fields in form%}
            <div class="col-6">
                <div class="form-floating mb-3">
                    {{fields.label}}
                    {{fields}}
                    
                </div>
            </div>
            {% endfor %}
        </div>
      
        <div class="row">
            <button type="submit"  class="btn btn-warning rounded-pill my-2">Update</button>
        </div>
    </form>
    </div>
</div>


{% endblock content %}